### ISSUE TITLE
Improve portability of non-published sites

### ISSUE THREAD

**Issue by rickhumphries** [elmsln/HAXcms#296] opened 2019-06-26 20:17 UTC
Forked hax-the-web as per #294 
Set up WAMP as instructed in the docs (same kind of deal as MAMP)
Started the servers and checked that PHP version is 7.2

Site kind of loads, but not properly:

I get this

![image](https://user-images.githubusercontent.com/4973810/60211769-b6ebe380-9857-11e9-97a1-b5ab103f5905.png)

Then scroll down and I've being told to update my browser (I'm on the latest version of Chrome)

![image](https://user-images.githubusercontent.com/4973810/60211825-d256ee80-9857-11e9-85e5-536c622896ae.png)

**Comment by btopro** [comment] 2019-06-26 20:35
Look and see if the build directory is there. If not type on -s ../../build when inside the site directory in terminal

**Comment by rickhumphries** [comment] 2019-06-26 22:08
hmm, ok, I think I see what I've done. I'm just trying to edit the site, but it's just standalone and haven't got it as part of HAXcms. I'll try again tomorrow

**Comment by btopro** [comment] 2019-06-27 12:30
ohhhhh I see. I thought you had it in the context of HAXcms. HAXcms brings in the editing capabilities. It not loading after a clone has been brought up, has to do w/ knowing where the files are. I've discussed some ways of possibly handling that more gracefully but if you copy the build directory from a HAXcms instance and put it in the site itself then it'll load locally in WAMP as a stand alone (or should).

The issue is that currently our "publishing step" corrects the path differences between a static copy and the real deal. Definitely something we need to improve the UX of

**Comment by btopro** [comment] 2019-08-06 16:34
duplicate of #296

**Comment by btopro** [comment] 2019-08-06 16:35
#287 rather

**Closed by btopro** 2019-08-06 16:34 UTC
Labels: bug
