### ISSUE TITLE
Site index listing and navigation out of order

### ISSUE THREAD

**Issue by lauragibbs** [elmsln/HAXcms#295] opened 2019-06-25 21:30 UTC
I just added the 5 new stories for today (yay!), and now something very weird is happening; I've been using a page-naming convention to keep the items in order, but they are now out of order in the left-hand site index and also in the page to page navigation buttons at the top of each page. I didn't do anything different (that I know of)... I added the new pages one by one today, and unfortunately I didn't happen to notice when the index listing started to look weird, but it does look weird now. The new pages I added are S000015, S000016, S000017, S000018, S000019, S000020, and they are all scattered around in there. I have no idea what ordering principle it's using. It just looks kind of wild!

https://hax.lauragibbs.net/sites/story-folder/

![Screen Shot 2019-06-25 at 5 24 09 PM](https://user-images.githubusercontent.com/19476543/60134926-9eec6500-976e-11e9-86ea-ee43e58a856e.png)

**Comment by btopro** [comment] 2019-06-25 21:54
Hmm.. this might be defaulting to an alphabetical sorta but not positive. If you click the outline button are you able to re-order things to be in the order you want just clicking in a row and hitting the up / down arrows it provides? 
![2019-06-25_17-53-38](https://user-images.githubusercontent.com/329735/60136456-33a49200-9772-11e9-89db-d4986b30721f.png)

**Comment by lauragibbs** [comment] 2019-06-25 22:03
I'll try that now. I didn't want to mess with the outline feature because I was expecting it to default to alphabetical, and that was fine with me. I'll go try manually adjusting in the outline.
But here's the thing: until now, it was alphabetical by page name OR by date created (since those would be the same in my system)... but something definitely made it go all wild. 
I'll go try manually adjusting now (but when I get to having hundreds of pages, manually adjusting is not going to work).

**Comment by lauragibbs** [comment] 2019-06-25 22:07
Okay, I can click and move, but it will be a TON of clicks to put it back in order. Should I put in a feature request to sort the outline by page name, by date created, etc.? Those would seem like logical options for people who do not want to be doing that manually. I am following a file-naming convention that would work for that purpose (alphabetical).
I'm also really baffled as to why it switched order on me...? It was fine up until whatever (?) happened today.

**Comment by lauragibbs** [comment] 2019-06-25 22:07
Thinking also that I really don't want to put it all manually back in order just to have it go all weird on me again ha ha

**Comment by btopro** [comment] 2019-06-25 22:14
hmm.. are you adding pages by just hitting the (+) button? trying to figure out how to back trace how that happened. Yeah I can understand that. A sort enforcement setting isn't a bad idea (by date, title, etc)

**Comment by lauragibbs** [comment] 2019-06-25 22:17
Yes, I hit this button in the blue editing bar; I usually create the 5 new pages, and then I go back and fill in the content one by one. I've done that four times so far (my goal is 5 stories per day), and today is the first day it got weird. For what it's worth, I was troubleshooting the image problem and editing that page before I created the new ones...? That page is: https://hax.lauragibbs.net/sites/story-folder/s000014 (I was really banging away on that one just trying to figure out the image thing).

Here's the button I use:

![Screen Shot 2019-06-25 at 6 16 02 PM](https://user-images.githubusercontent.com/19476543/60137629-79af2500-9775-11e9-9f1d-3f60094a5e35.png)

**Comment by btopro** [comment] 2019-06-25 22:20
thank you; I'll have to look at what the defaults are. It's most likely not aware of what to sort by in this situation but I'll have to dig a bit deeper. FWIW I use Outline in the haxtheweb site to add pages all the time. In my own blog tho when I hit the (+) I've previously seen it added as the 2nd item in the list... with no real rationale as to why it shows up there.

**Comment by lauragibbs** [comment] 2019-06-25 22:34
I'll try to do some weird things when I add more stories tomorrow to see if I get some insight with stories 21-25 :-)

**Comment by lauragibbs** [comment] 2019-06-26 19:34
Update on today's data entry. I decided to add the pages while looking at the About page. I used the + button, and added the pages one by one: S000021, S000022, S000023, S000024, S000025.
Total weirdness resulted, ha ha. They ARE all at the top (which is not where I wanted them), and they are also not in order. I have no idea why they are showing up in this strange order, but maybe it will be a good clue to use in debugging.
I can keep on editing the content,  so there's no rush about figuring out this weird navigation thing. I'll try a different process for adding pages tomorrow to see what I can learn then. :-)

![Screen Shot 2019-06-26 at 3 31 44 PM](https://user-images.githubusercontent.com/19476543/60209010-be939400-9827-11e9-9c5b-3b1004da562f.png)

**Comment by btopro** [comment] 2019-06-26 19:41
So tomorrow, can you add them via the outline and see if they do sit where you tell them to in that method?

**Comment by lauragibbs** [comment] 2019-06-26 19:48
Great! I will explore that tomorrow.
Other than the index weirdness, this is working PERFECTLY as an online notebook. Thank you!!!!! :-)

**Comment by lauragibbs** [comment] 2019-06-27 18:27
Started at site home directory:
https://hax.lauragibbs.net/sites/story-folder/
Clicked on Outline in blue editing bar, but I don't see any option to add pages there? I see duplicate button, but not add...?
Since I didn't see an add button in the outline menu options, I went to last page added as the experiment for today. So, I'm looking at this page:
https://hax.lauragibbs.net/sites/story-folder/s000025
(which is currently item #4 in the site index panel / outline)
There I clicked on Add button to add the new pages in this order: S000026, S000027, S000028, S000029, and S000030.
Instead of adding them in order after S000025 as I expected, it just looks totally weird again, as you can see in the screenshot.
I added them in order: 20-21-22-23-24-25-26-27-28-29-30
You can see they are 28-27-25-23-30-22-29-21-24-26
It's like some brain teaser to figure out what pattern that is! :-)
Anyway, I can keep on adding content, no problem, but I really am baffled by the strange order in which the new pages I'm adding are showing up in the index. Even more so because, until yesterday, I was not having this problem at all; everything was going right in order as expected/needed. 

![Screen Shot 2019-06-27 at 2 22 26 PM](https://user-images.githubusercontent.com/19476543/60290713-53a99200-98e7-11e9-8c10-ea7abead57d7.png)

**Comment by btopro** [comment] 2019-06-27 19:15
So when in the outliner if you hit enter you can make new pages. Think of it like an outline sitting in a word/google doc where you can just make an outline by using tab keys, typing and enter. We should add a but specifically for adding though that's a good point. Similarly you can delete pages by just removing them from the outline so it's a more aggressive changes type of interface.

**Comment by lauragibbs** [comment] 2019-06-27 19:18
Aha! Got it! I will try that tomorrow (Friday). Seeing the button for "duplicate" through me off. I'll report back tomorrow. 
And tomorrow will be my last day adding stories from Waters' Hampton book so I'll get to choose another book to start snagging stories from this weekend. Whoo-hoo! :-)

**Comment by lauragibbs** [comment] 2019-06-28 16:47
I went to https://hax.lauragibbs.net/sites/story-folder/
Clicked on outline icon in blue editing bar
While looking at Outline display, I went down to the bottom (currently S000020) and hit enter; it created a blank. I put all five new files for today there, then I hit save. Those are showing up as expected at the bottom! 

So, that's great; I will use that method from now on. 

But I'm going to leave the weird ordering of the rest of the files for now, hoping that you can (1) use that to find the bug, and (2) eventually come up with a way to reorder pages based on page name (my strategy), or date created, or date last updated (I can imagine people might want those options, right?).

My guess is people are more likely to use the plus button in the blue editing bar than hitting enter in the Outline mode. I never would have even guessed to do that if you have not told me. But for my purposes, that method is going to work perfectly!

OK! Files added. Now I will go fill in content. :-)

Happy Friday!

**Comment by lauragibbs** [comment] 2019-07-06 15:07
Just a quick note to say I've got a totally wild hodge-podge arrangement in the index sidebar at my site now: 
https://hax.lauragibbs.net/sites/story-folder/

It's not a big deal per se, but the real problem is that it makes a mess of the back-and-forward buttons which appear on every page in the site. For those back-and-forward navigation buttons to be useful, they need to be connected to a real arrangement of the pages in the index, and I don't want to be trying to manage that manually; there needs to be some kind of alphabetical default, maybe along with other defaults that are available in the system (like by date created oldest/newest, date edited oldest/newest...?). For people who want to manually arrange, the outline up-and-done can work (but it quickly becomes impractical with a large number of files also).

Anyway, I'm adding files and editing them without any problem, but at some point I'll need a way to clean up the hodge-podge way that items appear in the sidebar and backward-forward navigation buttons.

![Screen Shot 2019-07-06 at 11 06 55 AM](https://user-images.githubusercontent.com/19476543/60757871-35761d00-9fde-11e9-97eb-da080f6d58aa.png)

**Comment by btopro** [comment] 2019-08-06 15:30
duplicate of #321 and #329.

**Closed** 2019-08-06 16:33 UTC
Labels: UX, bug, outline editor
